### PR TITLE
Add about page and include a list of staff

### PR DESCRIPTION
**Pull request by yungyuc**
Team, please comment how you want your name appear in the list.  The possible formats are:

* Twitter handle: `Your Name <https://twitter.com/username>`
* Linkedin handle: `Your Name <https://www.linkedin.com/in/username>`
* Facebook handle: `Your Name <https://www.facebook.com/username>`
* Telegram: `Your Name <https://t.me/username>`
* Email: `Your Name <username@mail.server>`
* Bare name: `Your Name`
* Other

(issue #35)

### CODE REVIEW

**Comment by plChao** [comment]
Ping-Lien Chao <https://twitter.com/poseidon3141592>

**Comment by ghost** [comment]
Yu-Fang Hu yuko29.cs07@nctu.edu.tw

**Comment by ilikeazuresky0716** [comment]
Chi-Ching Lin <vickykciv520.dhss07@nctu.edu.tw>

**Comment by tenacity0310** [comment]
Tsung-Hsien Peter Li thpeterli@gmail.com

**Comment by yungyuc** [comment]
Merge the information collected so far.  Additional information uses a new PR.

**Comment by kunxianhuang** [comment]
Kunxian Huang kunxianh@outlook.com

**Comment by YenPeiChen07** [comment]
Jenny Yen  jenny35006@gmail.com

**Comment by sophiiim05g** [comment]
Shu-Fen Yu yu.sophi@gmail.com

**Pull request merged**
